---
name: Pipeline for capstone project abril
on:
  push:
    branches:
      - testworkflows
  pull_request:
      branches:
      - testworkflows
jobs:
    firstjob:
       name: Pipeline for capstone project abril
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v1
        - name: Accessing the hello_world project 
          run: cd capstone_project/hello-world/
        - name: installing dependencies
          working-directory: capstone_project/hello-world/
          run: npm install
        - name: Returning to original text
          working-directory: capstone_project/hello-world/src
          run: |
               sed -i 's/Hello DevOps!/Hello World!/g' App.js
        - name: Running test
          working-directory: capstone_project/hello-world/
          run: npm test
          if: ${{ success() }}
        - name: Building the container
          working-directory: capstone_project/hello-world/
          run: docker compose up -d
