---
name: Pipeline for capstone project
on:
  push:
    branches:
      - testworkflows
  pull_request:
      branches:
      - testworkflows
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
        - name: Acceder a la carpeta my_folder
          run: cd ./capstone_project
        - name: Imprimir directorio actual
          run: pwd
        - name: Running tests
          run: npm install && npm test && docker compose up
