---
name: Pipeline for capstone project
on:
  push:
    branches:
      - testworkflows
  pull_request:
      branches:
      - testworkflows
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
        - name: Verificar ruta y contenido
          run: |
               pwd
               ls -l capstone-project/hello-world
        - name: Prueba carpeta
          run: cd DevOps
        - name: Imprimir directorio actual1
          run: pwd
        - name: Running tests
          run: npm install && npm test && docker compose up
