---
name: Pipeline for capstone project
on:
  push:
    paths:
      - 'capstone_project/hello-world/**'
  pull_request:
      paths:
      - 'capstone_project/hello-world/**'
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
       - name: Running tests
         run: npm test && docker compose up
