---
name: Pipeline for capstone project
on:
  push:
    branches:
      - testworkflows
  pull_request:
      branches:
      - testworkflows
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v1
        - name: If tests are success, building the container
          run: cd capstone_project/hello-world/ && npm install && npm test && docker compose up
