---
name: Pipeline for capstone project
on:
  push:
    branches:
      - testworkflows
  pull_request:
      branches:
      - testworkflows
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v1
        - name: Cambiando de directorio
          run: cd capstone_project/hello-world/
        - name: Running tests
          run: npm install && npm test && docker compose up
