---
name: Pipeline for capstone project
on:
  push:
    branches:
      - testworkflows
  pull_request:
      branches:
      - testworkflows
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
        - name: uno
          run:  pwd
        - name: dos
          run: ls
        - name: tres
          run: cd ..
        - name: cuatro
          run: ls
        - name: Imprimir directorio actual1
          run: pwd
     #  - name: Running tests
      #    run: npm install && npm test && docker compose up
