---
name: Pipeline for capstone project
on:
  push: null
  pull_request: null
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
       - name: accediendo al proyecto
         run: cd capstone_project/hello-world
       - name: Running tests
         run: npm test && docker compose up
