---
name: Pipeline for capstone project
on:
  push:
    branches:
      - testworkflows
  pull_request:
      branches:
      - testworkflows
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
        - name: Dar permisos de ejecución al script
          run: chmod +x capstone_project/hello-world
        - name: Prueba carpeta
          run: capstone_project/hello-world
        - name: Imprimir directorio actual1
          run: pwd
        - name: Running tests
          run: npm install && npm test && docker compose up
